const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const { courseTitle, courseCode, content, generatedAt, sourceCount } = await req.json()

    if (!content) {
      return new Response(JSON.stringify({ error: 'Missing content' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    // Generate HTML for PDF rendering
    const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>${courseCode || ''} - ${courseTitle || 'Study Note'}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@400;600;700&family=JetBrains+Mono:wght@400;500&display=swap');
  
  body {
    font-family: 'Source Serif 4', Georgia, serif;
    max-width: 800px;
    margin: 0 auto;
    padding: 40px;
    color: #1a1a2e;
    line-height: 1.7;
    font-size: 12pt;
  }
  
  .header {
    border-bottom: 3px solid #22c55e;
    padding-bottom: 16px;
    margin-bottom: 32px;
  }
  
  .header h1 {
    color: #166534;
    font-size: 24pt;
    margin: 0 0 8px 0;
  }
  
  .header .meta {
    color: #666;
    font-size: 10pt;
  }
  
  h2 {
    color: #166534;
    border-bottom: 1px solid #22c55e;
    padding-bottom: 4px;
    margin-top: 24px;
  }
  
  h3 { color: #15803d; }
  
  code {
    font-family: 'JetBrains Mono', monospace;
    background: #f1f5f9;
    padding: 2px 6px;
    border-radius: 4px;
    font-size: 10pt;
  }
  
  pre {
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 8px;
    padding: 16px;
    overflow-x: auto;
  }
  
  pre code {
    background: none;
    padding: 0;
  }
  
  .footer {
    margin-top: 40px;
    padding-top: 16px;
    border-top: 2px solid #22c55e;
    font-size: 9pt;
    color: #666;
    text-align: center;
  }
</style>
</head>
<body>
  <div class="header">
    <h1>${courseCode || ''} — ${courseTitle || 'Study Note'}</h1>
    <div class="meta">
      Generated: ${generatedAt ? new Date(generatedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : 'N/A'}
      | Sources: ${sourceCount || 0} contributions
      | CyberWiki — University of Port Harcourt
    </div>
  </div>
  <div class="content">${markdownToHtml(content)}</div>
  <div class="footer">
    CyberWiki Study Note — ${courseCode} — Generated by AI from ${sourceCount || 0} peer contributions
  </div>
</body>
</html>`

    return new Response(JSON.stringify({
      html,
      generatedAt: new Date().toISOString(),
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  } catch (e) {
    return new Response(JSON.stringify({ error: 'Export failed', details: String(e) }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})

function markdownToHtml(md: string): string {
  return md
    .replace(/^### (.*$)/gm, '<h3>$1</h3>')
    .replace(/^## (.*$)/gm, '<h2>$1</h2>')
    .replace(/^# (.*$)/gm, '<h1>$1</h1>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/```[\s\S]*?```/g, (match) => {
      const code = match.replace(/```\w*\n?/, '').replace(/```$/, '')
      return `<pre><code>${code}</code></pre>`
    })
    .replace(/^\- (.*$)/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>)/s, '<ul>$1</ul>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/^(.+)$/gm, (line) => {
      if (line.startsWith('<')) return line
      return `<p>${line}</p>`
    })
}
