// src/components/admin/KBManagementTab.tsx
// Admin interface for generating, reviewing, and publishing knowledge bases.
// Each KB is generated by the generate-knowledge-base edge function,
// reviewed by an admin, then marked is_ready=true so tutors can use it.

import { useState, useEffect, useCallback } from 'react';
import { Sparkles, CheckCircle, Clock, AlertCircle, Eye, EyeOff, RefreshCw, BookOpen, Brain, Zap } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { CAREERS } from '@/lib/tutor-data';
import { toast } from 'sonner';
import SafeMarkdown from '@/components/SafeMarkdown';

interface KBRecord {
  id: string;
  type: string;
  entity_id: string;
  title: string;
  word_count: number;
  is_ready: boolean;
  generated_by: string;
  last_generated_at: string | null;
  updated_at: string;
}

interface AILiteracyTopic {
  career_id: string;
  slug: string;
  title: string;
  description: string | null;
}

const TYPE_LABELS: Record<string, string> = {
  career_path: '🗺️ Career Path KB',
  career_topic: '📖 Career Topic KB',
  ai_literacy: '🤖 AI Literacy (Career Overview)',
  ai_literacy_topic: '🤖 AI Literacy Topic',
  course_topic: '📚 Course Topic KB',
};

async function callGenerateKB(
  type: string,
  entityId: string,
  params: Record<string, string>,
  token: string
): Promise<boolean> {
  const res = await fetch(
    `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/generate-knowledge-base`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
        apikey: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
      },
      body: JSON.stringify({ type, entityId, ...params }),
    }
  );
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(err.error || res.statusText);
  }
  return true;
}

async function getToken(): Promise<string> {
  const { data } = await supabase.auth.getSession();
  return data.session?.access_token ?? '';
}

export default function KBManagementTab() {
  const [kbs, setKBs] = useState<KBRecord[]>([]);
  const [aiTopics, setAITopics] = useState<AILiteracyTopic[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState<string | null>(null);
  const [previewId, setPreviewId] = useState<string | null>(null);
  const [previewContent, setPreviewContent] = useState('');
  const [previewLoading, setPreviewLoading] = useState(false);

  // Generation form
  const [selectedCareer, setSelectedCareer] = useState(CAREERS[0]?.id ?? '');
  const [genType, setGenType] = useState<'career_path' | 'ai_literacy' | 'ai_literacy_topic'>('career_path');
  const [selectedTopic, setSelectedTopic] = useState('');

  const loadKBs = useCallback(async () => {
    const { data } = await supabase
      .from('knowledge_bases')
      .select('id, type, entity_id, title, word_count, is_ready, generated_by, last_generated_at, updated_at')
      .order('type').order('entity_id');
    setKBs(data ?? []);
  }, []);

  const loadAITopics = useCallback(async () => {
    const { data } = await supabase
      .from('ai_literacy_topics')
      .select('career_id, slug, title, description')
      .order('career_id').order('topic_order');
    setAITopics(data ?? []);
  }, []);

  useEffect(() => {
    setLoading(true);
    Promise.all([loadKBs(), loadAITopics()]).finally(() => setLoading(false));
  }, [loadKBs, loadAITopics]);

  const careerTopicsForSelected = aiTopics.filter(t => t.career_id === selectedCareer);

  const generate = async () => {
    const career = CAREERS.find(c => c.id === selectedCareer);
    if (!career) return;
    const tok = await getToken();
    let entityId = '';
    let params: Record<string, string> = { careerId: selectedCareer, careerTitle: career.title };

    if (genType === 'career_path') {
      entityId = selectedCareer;
    } else if (genType === 'ai_literacy') {
      entityId = `${selectedCareer}::ai-literacy`;
    } else if (genType === 'ai_literacy_topic') {
      if (!selectedTopic) { toast.error('Select a topic first'); return; }
      const topic = careerTopicsForSelected.find(t => t.slug === selectedTopic);
      if (!topic) { toast.error('Topic not found'); return; }
      entityId = `${selectedCareer}::${selectedTopic}`;
      params = { ...params, topicTitle: topic.title, topicDescription: topic.description ?? '' };
    }

    setGenerating(entityId);
    toast.info(`Generating ${TYPE_LABELS[genType]} for ${career.title}… (this takes 15–45 seconds)`);

    try {
      await callGenerateKB(genType, entityId, params, tok);
      toast.success('Generated! Review it below, then mark it Ready.');
      await loadKBs();
    } catch (e) {
      toast.error('Generation failed: ' + (e as Error).message);
    }
    setGenerating(null);
  };

  const toggleReady = async (kb: KBRecord) => {
    const { error } = await supabase
      .from('knowledge_bases')
      .update({ is_ready: !kb.is_ready, updated_at: new Date().toISOString() })
      .eq('id', kb.id);
    if (error) { toast.error('Update failed'); return; }
    setKBs(prev => prev.map(k => k.id === kb.id ? { ...k, is_ready: !kb.is_ready } : k));
    toast.success(kb.is_ready ? 'KB unpublished — tutors will use fallback' : 'KB published ✓ — tutors will now use this');
  };

  const loadPreview = async (kb: KBRecord) => {
    if (previewId === kb.id) { setPreviewId(null); return; }
    setPreviewId(kb.id);
    setPreviewLoading(true);
    const { data } = await supabase.from('knowledge_bases').select('content').eq('id', kb.id).maybeSingle();
    setPreviewContent(data?.content ?? '');
    setPreviewLoading(false);
  };

  const readyKBs = kbs.filter(k => k.is_ready);
  const draftKBs = kbs.filter(k => !k.is_ready);
  const totalWords = readyKBs.reduce((s, k) => s + (k.word_count ?? 0), 0);

  return (
    <div className="space-y-6">
      {/* Stats */}
      <div className="grid grid-cols-3 gap-4">
        {[
          { label: 'Published KBs', value: readyKBs.length, icon: CheckCircle, color: 'text-primary' },
          { label: 'Drafts (review needed)', value: draftKBs.length, icon: Clock, color: 'text-yellow-400' },
          { label: 'Total Words Published', value: totalWords.toLocaleString(), icon: BookOpen, color: 'text-foreground' },
        ].map(s => (
          <div key={s.label} className="card-cyber p-4 text-center">
            <s.icon className={`w-5 h-5 ${s.color} mx-auto mb-1`} />
            <p className="text-lg font-bold text-foreground font-mono">{s.value}</p>
            <p className="text-xs text-muted-foreground">{s.label}</p>
          </div>
        ))}
      </div>

      {/* Generation form */}
      <div className="card-cyber p-5">
        <div className="flex items-center gap-2 mb-4">
          <Sparkles className="w-4 h-4 text-primary" />
          <h3 className="font-semibold text-foreground">Generate Knowledge Base</h3>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-4">
          <div>
            <label className="text-xs text-muted-foreground mb-1 block">Career Path</label>
            <select value={selectedCareer} onChange={e => setSelectedCareer(e.target.value)}
              className="w-full px-3 py-2 rounded-lg bg-background border border-border text-sm text-foreground focus:border-primary focus:outline-none">
              {CAREERS.filter(c => c.id !== 'ai-security').map(c => (
                <option key={c.id} value={c.id}>{c.emoji} {c.title}</option>
              ))}
            </select>
          </div>
          <div>
            <label className="text-xs text-muted-foreground mb-1 block">KB Type</label>
            <select value={genType} onChange={e => setGenType(e.target.value as typeof genType)}
              className="w-full px-3 py-2 rounded-lg bg-background border border-border text-sm text-foreground focus:border-primary focus:outline-none">
              <option value="career_path">Career Path KB (full)</option>
              <option value="ai_literacy">AI Literacy Overview (career)</option>
              <option value="ai_literacy_topic">AI Literacy Topic (specific)</option>
            </select>
          </div>
          {genType === 'ai_literacy_topic' && (
            <div>
              <label className="text-xs text-muted-foreground mb-1 block">Topic</label>
              <select value={selectedTopic} onChange={e => setSelectedTopic(e.target.value)}
                className="w-full px-3 py-2 rounded-lg bg-background border border-border text-sm text-foreground focus:border-primary focus:outline-none">
                <option value="">Select topic…</option>
                {careerTopicsForSelected.map(t => (
                  <option key={t.slug} value={t.slug}>{t.title}</option>
                ))}
              </select>
            </div>
          )}
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={generate}
            disabled={!!generating || (genType === 'ai_literacy_topic' && !selectedTopic)}
            className="flex items-center gap-2 px-5 py-2.5 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:bg-primary/90 disabled:opacity-50 min-h-[40px]"
          >
            {generating ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Zap className="w-4 h-4" />}
            {generating ? 'Generating…' : 'Generate'}
          </button>
          <p className="text-xs text-muted-foreground">
            Career Path and AI Literacy KBs take 30–60 seconds. Review before publishing.
          </p>
        </div>
      </div>

      {/* Draft KBs (awaiting review) */}
      {draftKBs.length > 0 && (
        <div>
          <h3 className="text-sm font-semibold text-yellow-400 uppercase tracking-wide mb-3 flex items-center gap-2">
            <AlertCircle className="w-4 h-4" /> Awaiting Review ({draftKBs.length})
          </h3>
          <div className="space-y-3">
            {draftKBs.map(kb => (
              <KBCard key={kb.id} kb={kb} onToggleReady={toggleReady} onPreview={loadPreview}
                isPreviewOpen={previewId === kb.id} previewContent={previewContent} previewLoading={previewLoading} />
            ))}
          </div>
        </div>
      )}

      {/* Published KBs */}
      {readyKBs.length > 0 && (
        <div>
          <h3 className="text-sm font-semibold text-primary uppercase tracking-wide mb-3 flex items-center gap-2">
            <CheckCircle className="w-4 h-4" /> Published ({readyKBs.length})
          </h3>
          <div className="space-y-3">
            {readyKBs.map(kb => (
              <KBCard key={kb.id} kb={kb} onToggleReady={toggleReady} onPreview={loadPreview}
                isPreviewOpen={previewId === kb.id} previewContent={previewContent} previewLoading={previewLoading} />
            ))}
          </div>
        </div>
      )}

      {!loading && kbs.length === 0 && (
        <div className="text-center py-12">
          <Brain className="w-12 h-12 text-muted-foreground mx-auto mb-4 opacity-40" />
          <p className="text-muted-foreground text-sm">No knowledge bases generated yet.</p>
          <p className="text-muted-foreground text-xs mt-1">Use the form above to generate your first KB. Start with Career Path KBs.</p>
        </div>
      )}
    </div>
  );
}

function KBCard({ kb, onToggleReady, onPreview, isPreviewOpen, previewContent, previewLoading }: {
  kb: KBRecord;
  onToggleReady: (kb: KBRecord) => void;
  onPreview: (kb: KBRecord) => void;
  isPreviewOpen: boolean;
  previewContent: string;
  previewLoading: boolean;
}) {
  return (
    <div className="card-cyber p-4">
      <div className="flex items-start justify-between flex-wrap gap-3">
        <div>
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-xs text-muted-foreground font-mono">{TYPE_LABELS[kb.type] ?? kb.type}</span>
            {kb.is_ready
              ? <span className="text-xs px-2 py-0.5 rounded-full bg-primary/15 text-primary border border-primary/20">✓ Live</span>
              : <span className="text-xs px-2 py-0.5 rounded-full bg-yellow-400/15 text-yellow-400 border border-yellow-400/20">Draft</span>}
          </div>
          <p className="font-semibold text-foreground text-sm mt-1">{kb.title}</p>
          <p className="text-xs text-muted-foreground font-mono mt-0.5">{kb.entity_id}</p>
          {kb.word_count && (
            <p className="text-xs text-muted-foreground mt-0.5">{kb.word_count.toLocaleString()} words</p>
          )}
        </div>
        <div className="flex gap-2 flex-wrap">
          <button onClick={() => onPreview(kb)}
            className="flex items-center gap-1 px-3 py-1.5 rounded-lg bg-secondary text-muted-foreground hover:text-foreground text-xs min-h-[34px]">
            {isPreviewOpen ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
            {isPreviewOpen ? 'Hide' : 'Preview'}
          </button>
          <button onClick={() => onToggleReady(kb)}
            className={`flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs min-h-[34px] transition-colors ${
              kb.is_ready
                ? 'border border-orange-400/40 text-orange-400 hover:bg-orange-400/10'
                : 'bg-primary/10 border border-primary/30 text-primary hover:bg-primary/20'
            }`}>
            {kb.is_ready ? 'Unpublish' : 'Publish'}
          </button>
        </div>
      </div>

      {isPreviewOpen && (
        <div className="mt-4 border-t border-border pt-4">
          {previewLoading
            ? <p className="text-xs text-muted-foreground animate-pulse">Loading preview…</p>
            : <div className="max-h-96 overflow-y-auto">
                <SafeMarkdown content={previewContent} className="text-sm" />
              </div>}
        </div>
      )}
    </div>
  );
}
